---
ansible_connection: local

openshift_cluster_content:
- object: keycloak-custom-resources
  content:
  - name: keycloak_crds
    file: "{{ inventory_dir }}/../templates/keycloak/operator-crds.yaml"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - operators
    - keycloak
    - keycloak-operator
    - operator-crds