---
ansible_connection: local

build:
  NAME: '{{ app_name }}'

surveydb:
  DATABASE_SERVICE_NAME: 'surveydb'
  POSTGRESQL_DATABASE: 'surveydb'
  VOLUME_CAPACITY: '5Gi'
  POSTGRESQL_PASSWORD: 'somepassword'
  POSTGRESQL_USER: 'someusername'

openshift_cluster_content:
  - object: app-builds
    content:
    - name: survey-db
      template: openshift//postgresql-persistent
      params_from_vars: "{{ surveydb }}"
      namespace: "{{ dev_namespace }}"
      tags:
      - app-dev-deploy
      - survey-db-deploy
    - name: survey-db
      template: openshift//postgresql-persistent
      params_from_vars: "{{ surveydb }}"
      namespace: "{{ test_namespace }}"
      tags:
      - app-test-deploy
      - survey-db-deploy
    - name: survey-db
      template: openshift//postgresql-persistent
      params_from_vars: "{{ surveydb }}"
      namespace: "{{ demo_namespace }}"
      tags:
      - app-demo-deploy
      - survey-db-deploy

