---
ansible_connection: local

build:
  NAME: '{{ app_name }}'

surveydb:
  DATABASE_SERVICE_NAME: 'surveydb'
  POSTGRESQL_DATABASE: 'surveydb'
  VOLUME_CAPACITY: '5Gi'
  POSTGRESQL_PASSWORD: 'somepassword'
  POSTGRESQL_USER: 'someusername'

openshift_cluster_content:
  - object: app-builds
    content:
      - name: survey-spring-service-cicd
        template: '{{ playbook_dir }}/templates/survey-spring-service-cicd.yml'
        params: "{{ playbook_dir }}/params/survey-spring-service-cicd"
        namespace: "{{ ci_cd_namespace }}"
        tags:
        - ci-cd
        - survey-spring-service
      - name: surveydb
        template: openshift//postgresql-persistent
        params_from_vars: "{{ surveydb }}"
        namespace: "{{ dev_namespace }}"
        tags:
        - dev
        - surveydb
      - name: survey-spring-service-resources
        template: '{{ playbook_dir }}/templates/survey-spring-service-resources.yml'
        params: "{{ playbook_dir }}/params/survey-spring-service-resources"
        namespace: "{{ dev_namespace }}"
        tags:
        - dev
        - survey-spring-service

