---
apiVersion: v1
kind: Template
metadata:
  name: Dockerfile Build Template FROM DockerImage
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: "${NAME}"
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: "${NAME}"
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: '${NAME}:latest'
    resources: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: "${SOURCE_IMAGE}"
        dockerfilePath: "${DOCKERFILE_PATH}"
    postCommit: {}
    source:
      type: Git
      git:
        uri: "${REPOSITORY_URL}"
    triggers:
      - type: ConfigChange
      - type: ImageChange
    runPolicy: Serial
  status: {}
parameters:
- name: NAME
  value: nexus-kubernetes
  description: The name for the output imagestream and buildconfig
- name: REPOSITORY_URL
  value: https://github.com/sonatype-nexus-community/nexus-kubernetes-openshift.git
  description: The URL for the source code repository containing the Dockerfile
- name: DOCKERFILE_PATH
  value: Dockerfile
  description: The relative path within the repository to the Dockerfile
- name: SOURCE_IMAGE
  value: sonatype/nexus3:latest
  description: The base image for the Dockerfile build