---
app_name: consultant-360-fe

namespace_prefix: consultant-360

ci_cd_namespace: "{{ namespace_prefix }}-ci-cd"
dev_namespace: "{{ namespace_prefix }}-dev"
test_namespace: "{{ namespace_prefix }}-test"
demo_namespace: "{{ namespace_prefix }}-demo"

openshift_templates_raw: "https://raw.githubusercontent.com/redhat-cop/openshift-templates"
openshift_templates_raw_version_tag: "v1.4.12"
cop_quickstarts: "https://github.com/redhat-cop/containers-quickstarts.git"
cop_quickstarts_raw: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts"
cop_quickstarts_raw_version_tag: "v1.14"

dev:
  NAMESPACE: "{{ dev_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ dev_namespace }}"

test:
  NAMESPACE: "{{ test_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ test_namespace }}"

ci_cd:
  NAMESPACE: "{{ ci_cd_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ ci_cd_namespace }}"

demo:
  NAMESPACE: "{{ demo_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ demo_namespace }}"

edit_role_binding_group:
  GROUP: "rhc-na-appdev-coe"
  ROLE: "{{ role | default('edit') }}"
admin_role_binding_group:
  GROUP: "rhc-na-appdev-coe-admins"
  ROLE: "admin"
